import Head from "next/head";
import { useRouter } from "next/router";

export default function Yippie() {
  const { query } = useRouter();
  const name = query.name as string;

  return (
    <div>
      <Head>
        <title>You did it!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>You did it, {name}!</h1>
    </div>
  );
}
